### ISSUE TITLE
Remove underlining

### ISSUE THREAD

**Issue by tsawitzki** [slim-template/language-slim#15] opened 2015-07-20 09:52 UTC
Hello, I get an underlining of every abstracted HTML-Element when I activate the Syntax-Highlighting. Is it meant to be like this? Otherwise: Any idea where this may come from? There are now settings for this. It really does not help the view imo …

**Comment by jessejanderson** [comment] 2016-02-08 06:58
Getting the same thing - it's incredibly distracting. Not feeling very encouraged that no one has replied to this 6 month old comment...

**Comment by vemv** [comment] 2016-10-09 12:26
Might be just me, but is underlining actually broken?

Note the trailing underscored area:

![image](https://cloud.githubusercontent.com/assets/1162994/19220372/222cb572-8e2c-11e6-9208-767a1a8a577e.png)

**Comment by aeyoa** [comment] 2017-04-20 22:05
I found the workaround for this annoying issue.

Open your custom styles

<img width="292" alt="screen shot 2017-04-21 at 01 02 08" src="https://cloud.githubusercontent.com/assets/6937970/25254437/37b17596-262e-11e7-8f3b-b2080ea365bc.png">

And add the following rules 
```less
atom-pane[data-active-item-name="item.html.slim"] {
  .syntax--entity.syntax--name.syntax--tag {
    text-decoration: none;
  }
}
```

This should hide the underlining.

**Comment by tsawitzki** [comment] 2017-04-21 09:42
Thanks @aeyoa, sounds like a perfect workaround!

**Comment by tshedor** [comment] 2017-10-25 19:31
All, closing this issue out because there aren't underlining styles in this repo and it's likely something added by your theme or HTML settings. If anyone is able to list their environment or steps to reproduce I can revisit, but in a default Atom editor I do not see tag underlining on Slim or HTML files.

**Closed by tshedor** 2017-10-25 19:31 UTC
